# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lidar.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0blidar.proto"*\n\x07Point3D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02"\x11\n\x0fGetLIDARRequest",\n\x10GetLIDARResponse\x12\x18\n\x06points\x18\x01 \x03(\x0b\x32\x08.Point3Db\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "lidar_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _POINT3D._serialized_start = 15
    _POINT3D._serialized_end = 57
    _GETLIDARREQUEST._serialized_start = 59
    _GETLIDARREQUEST._serialized_end = 76
    _GETLIDARRESPONSE._serialized_start = 78
    _GETLIDARRESPONSE._serialized_end = 122
# @@protoc_insertion_point(module_scope)
